notes:
  groups:
    elite:
      upgrade:
        name: "<b><green>%group% > %target_rank%"
        material: "PAPER"
        lore:
          - ""
      name: "<green>%group% <i><dark_gray>[Rank]"
      name-with-time-left: "<green>%group% <i><dark_gray>[%time_left% Day Rank]"
      material: "PAPER"
      lore:
        - ""
    legend:
      upgrade:
        name: "<b><yellow>%group% > %target_rank%"
        material: "PAPER"
        lore:
          - ""
      name: "<yellow>%group% <i><dark_gray>[Rank]"
      name-with-time-left: "<yellow>%group% <i><dark_gray>[%time_left% Day Rank]"
      material: "PAPER"
      lore:
        - ""
    jester:
      upgrade:
        name: "<b><red>%group% > %target_rank%"
        material: "PAPER"
        lore:
          - ""
      name: "<red>%group% <i><dark_gray>[Rank]"
      name-with-time-left: "<red>%group% <i><dark_gray>[%time_left% Day Rank]"
      material: "PAPER"
      lore:
        - ""
    default:
      upgrade:
        name: "<b><green>%group% > %target_rank%"
        material: "PAPER"
        lore:
          - ""
      name: "<aqua>%group% <i><dark_gray>[Rank]"
      name-with-time-left: "<aqua>%group% <i><dark_gray>[%time_left% Day Rank]"
      material: "PAPER"
      lore:
        - ""

group-progress:
  - elite
  - legend
  - jester


language: en