name: "MiniRanks"
version: "${version}"
authors:
  - SQD Studios

main: net.chamosmp.miniranks.MiniRanksPlugin
#Loader: net.chamosmp.

api-version: "1.21.11"
website: https://github.com/SQD-Studios/MiniRanks

folia-supported: true


dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: true
      join-classpath: true